### ISSUE TITLE
The scrollable area for the Response is greatly reduced

### ISSUE THREAD

**Issue by stajs** [lic-nz/Malone#36]
@jemerald We will have to re-think how we display large responses. The change to not show the entire response because of concerns with the performance of multi-megabyte sized responses, has lead to decreased utility for the general case:

![image](https://cloud.githubusercontent.com/assets/2253814/7625536/ea645218-fa4c-11e4-9fed-fd7deceeb7c3.png)

**Comment by jemerald** [comment]
Yes, this looks particularly bad when the authentication tab is selected and token text is displayed (my current token text takes up to 35 lines), this why my layout change PR uses a fixed proportion between request and response.

One thing I can think of, is to automatically reduce the entire request section when API response is received allowing better response viewing, then user can hover/click it to bring it back?

**Comment by stajs** [comment]
Yeah, in the case where you have a large auth token (or request body, or headers), you could quite easily not be able to see the response at all:

![image](https://cloud.githubusercontent.com/assets/2253814/7625522/c7fb29fe-fa4c-11e4-9103-3a2a1fc1495c.png)

**Comment by stajs** [comment]
This _might_ be of use (recording for investigation later): http://stackoverflow.com/questions/198656/nested-scroll-areas/1571972#1571972

**Comment by stajs** [comment]
I'm going to temporarily revert so there is a scroll viewer around everything, at the expense of performance for very large responses.

I'll set up the next priority issue to make the Request and Response sections separate tabs, so that the response body can use AvalonEdit's virtualizing functionality better.
