### ISSUE TITLE
MVVM pattern adherence

### ISSUE THREAD

**Issue by jemerald** [lic-nz/Malone#37]
There are a few things in the Malone project I consider breaking the MVVM pattern, i.e. things that are really a view's concern are done in the view-model.

Some examples from the AppViewModel class:

UI element size - HistoryHorizontalOffset, HistoryVerticalScrollBarOffset, etc. These should not be in the view model at all
UI specific values - DirtyVisibility, RequestHasResponseVisibility, etc. These should be replaced with boolean flags (e.g. IsDirty) and use converter in the view to turn the boolean value to whatever required.

**Comment by stajs** [comment]
Yep, you got me :grimacing:

Although in my arrogance I contend I am merely bending the rule: it's still a flag, just not a boolean :stuck_out_tongue_winking_eye:. Biggest annoyance with WPF is the amount of boilerplate you have to write. Converter for this, converter for that, bah! :rage4:

**Comment by jemerald** [comment]
I'm about to do some tidy ups in this space, the visibility flags are easy, so are the loca/utc time display.

But the HistoryHorizontalOffset & HistoryVerticalScrollBarOffset, they are used to position the delete button, correct? From what I can see, currently the binding works in the following way:
1. Event binding in MaloneListBox calls HistoryLayoutUpdated in the view model
2. HistoryHorizontalOffset & HistoryVerticalScrollBarOffset gets set
3. Two hidden labels gets their content updated
4. HistoryWidthConverter picks up the label content

That's a lot of hoops to jump through to achieve the button positioning, not to mention quite a few magic numbers used in various places.

There are a few ways to improve this:
1. have the HistoryWidthConverter bind directly to the properties of the listbox, which gets rid of all the intermediate steps
2. disable the horizontal scrolling, which removes the need of dynamic button positioning (button just need to be right aligned), long url will be truncated if the history panel is not wide enough, which matches what Postman does
3. move the delete button to the left

Personally I would prefer option 2, what do you think?

**Comment by stajs** [comment]
Yeah, some of those hoops were needed to support the dynamic width and having the delete button being snapped to the edge of the grid splitter rather than hidden underneath when scroll width is too wide. I'll be happy to not have it dynamic, so yeah option 2 is the best IMO.
