### ISSUE TITLE
Application crashed after returning large XML data

### ISSUE THREAD

**Issue by mattox** [lic-nz/Malone#44]
When attempting a GET for the datamate bulls list (over 10,000 animals) the application crashed. 

URL: http://itops-test.api.minda.livestock.org.nz/services/itoperations.datamate/v0/bulls/

**Comment by stajs** [comment]
Known issue, see #36 and #41. Also:

![image](https://cloud.githubusercontent.com/assets/2253814/7672386/fdcabee6-fd44-11e4-8523-770d60ba07b0.png)
