### ISSUE TITLE
Revert #71

### ISSUE THREAD

**Issue by stajs** [lic-nz/Malone#83]
https://github.com/lic-nz/Malone/pull/69#issuecomment-183973305

https://github.com/lic-nz/Malone/compare/v0.8.0...v0.9.1

- [x] Revert faulty PR
- [x] Move Authentication back to under URL (i.e.v0.8.0)

**Comment by stajs** [comment]
@raydenl We've *finally* gotten around to backing out the faulty PR that smashed your changes (moving the auth selector up a level for greater visibility). Can you check the latest canary build and give us a :shipit:? I'll give you a deadline of next Wednesday (March 9) to get back with any objections before we call it done and move forward.

/cc @nicojclic @toogooda

**Comment by raydenl** [comment]
I have given v0.9.5 a quick test and it seems to be working as expected


Rayden Lee
Senior Software Developer

[cid:logolic_gif_308D3DB4-C4BF-D542-5770-F48D7156E725]

Private Bag 3016 (Cnr Ruakura & Morrinsville Roads, Newstead)
Hamilton 3240 NEW ZEALAND

Phone: 07 981 7027
Web: www.lic.co.nz

________________________________
This message is for the named person's use only. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mis-transmission. If you receive this message in error, please immediately delete it and all copies of it from your system, destroy any hard copies of it and notify the sender. LIC reserves the right to monitor all e-mail communications through its networks. Although LIC regularly scans its computer systems for viruses using anti-virus software, LIC is not responsible for the consequences of any viruses, data corruption, interception or unauthorised amendment to this email. The recipient should check this email and any attachments for viruses and defects. This email does not designate an information system for the purposes of section 11(a) of the NZ Electronic Transactions Act 2002.

**Comment by stajs** [comment]
Sweet, thanks.

@VladMukhitdinovLic We can make it a public release on Monday.

**Comment by stajs** [comment]
RTM'd
